sacred:
  observer: mongodb  # mongodb or file_storage

  # Use the mongodb observer. Useful when access to a database server
  mongodb:
    url: "@{specific:sacred.mongo_db.url}"  # url of the mongodb server
    db_name: "@{specific:sacred.mongo_db.db_name}"  # name of the sacred database

  # Otherwise use the file storage and save on disk
  file_storage:
    path: "@{specific:sacred.file_storage.path}"
